all: matrixgen matrixver matrixcomp

matrixgen: matrixgen.c
	gcc -o matrixgen matrixgen.c

matrixver: matrixver.c
	gcc -o matrixver matrixver.c

matrixcomp: matrixcomp.c
	gcc -o matrixcomp matrixcomp.c

clean:
	rm -f matrixgen matrixver matrixcomp