all: ex1 ex2 ex3 ex4 ex5

ex1: ex1.c
	gcc -o ex1 ex1.c

ex2: ex2.c
	gcc -o ex2 ex2.c

ex3: ex3.c
	gcc -o ex3 ex3.c

ex4: ex4.c
	gcc -o ex4 ex4.c

ex5: ex5.c
	gcc -o ex5 ex5.c

clean:
	rm -f ex1 ex2 ex3 ex4 ex5