all: jerarquia1 jerarquia2

jerarquia1: jerarquia1.c error_exit.o
	gcc -o jerarquia1 jerarquia1.c error_exit.o
jerarquia2: jerarquia2.c error_exit.o
	gcc -o jerarquia2 jerarquia2.c error_exit.o

clean:
	rm -f jerarquia1 jerarquia2
	
    
