all: arith printints Mersenne

arith: arith.c
	gcc -o arith arith.c

printints: printints.c
	gcc -o printints printints.c

Mersenne: Mersenne.c
	gcc -o Mersenne Mersenne.c

clear: rm -f arith printints Mersenne